# Generated by Django 6.0.3 on 2026-05-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=150)),
                ('cpf_cliente', models.CharField(max_length=20, unique=True)),
                ('tel_cliente', models.CharField(max_length=20)),
                ('email_cliente', models.CharField(max_length=100)),
                ('endereco_cliente', models.TextField()),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('categoria_produto', models.CharField(max_length=50)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
        migrations.CreateModel(
            name='servicos',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora_agenda', models.DateTimeField()),
            ],
            options={
                'db_table': 'servicos',
            },
        ),
        migrations.CreateModel(
            name='pets',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pet', models.CharField(max_length=100)),
                ('especie_pet', models.CharField(max_length=50)),
                ('cor_pet', models.CharField(max_length=50)),
                ('peso_pet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dono', models.ForeignKey(db_column='dono_id', on_delete=django.db.models.deletion.CASCADE, to='agendamento.clientes')),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='agendamentos',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora_agendamento', models.DateTimeField()),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='agendamento.clientes')),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, to='agendamento.pets')),
                ('produto', models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.CASCADE, to='agendamento.produtos')),
                ('servico', models.ForeignKey(db_column='servico_id', on_delete=django.db.models.deletion.CASCADE, to='agendamento.servicos')),
            ],
            options={
                'db_table': 'agendamentos',
            },
        ),
    ]
