# Generated by Django 6.0.3 on 2026-05-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='agendamentos',
            new_name='Agendamento',
        ),
    ]
