# Generated by Django 6.0.3 on 2026-05-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_rename_agendamentos_agendamento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pets',
            table='agendamento_pets',
        ),
    ]
