# Generated by Django 6.0.3 on 2026-05-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_pets_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicos',
            table='agendamento_servicos',
        ),
    ]
