# Generated by Django 6.0.3 on 2026-05-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_alter_cliente_id_alter_cliente_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pet', models.CharField(max_length=100)),
                ('especie_pet', models.CharField(max_length=100)),
                ('idade_pet', models.IntegerField()),
                ('peso_pet', models.FloatField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'db_table': 'pets',
            },
        ),
    ]
