# Generated by Django 6.0.3 on 2026-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora_agenda', models.DateTimeField()),
            ],
            options={
                'db_table': 'servicos',
            },
        ),
    ]
